---
title: "About ManyLanguages"
---

## **Core Values**

-   **Diversity and inclusion**: Language research is a diverse field that intersects with numerous branches of qualitative and quantitative science. We encourage scientists from all fields to participate in ManyLanguages and support diversity in the types of projects, languages, participants, and researchers in our community.

-   **Transparency**: We engage in transparency on all policies, procedures, and projects. Each project will include a pre-registered plan. These plans may include a hypothesis, methods, and analysis for that specific research area. However, we encourage all types of projects, but they should include plans for the project to register and propose to collaborators. All policies are posted on our website for at-large review.

-   **Openness**: We believe that the languages sciences can only benefit from open sharing of research. When appropriate, data, code, materials, preprints, etc. will be shared in an open and reusable format. We strive to make these research outputs FAIR (findable, accessible, interoperable, and reusable) by posting to open source platforms and organising information. Given ethical concerns, we will strive to create synthetic or otherwise suitably anonymous research outputs.

-   **Responsiveness**: We expect a diversity of ideas and backgrounds within the ManyLanguages community. We will be responsive to criticism, challenges of beliefs, and other feedback within the guidelines of our code of conduct. Policies and procedures will be updated based on discussion and feedback from members.

## What ManyLanguages offers the community

-   ManyLanguages offers an environment that operates on a shared set of values on how to interact with each other (code of conduct) that is supposed to alleviate power asymmetries and diffuse interpersonal conflicts between collaborators. If you as a researcher align with our values, ManyLanguages represents a safe place for you to collaborate with others. 

-   ManyLanguages offers and curates a Canvas platform which allows members to connect to each other. Canvas allows us to organise relevant information in a consistent way and offers a consistent communication channel for all members of ManyLanguages. Having such an infrastructure in place allows for efficient workflows and communication.

-   ManyLanguages organises expert feedback on different stages of supported projects. For example, a pre-study review committee can give feedback on project proposals which helps improve proposals at the initial stages of a project. A post-study review committee can help ensure that all results of the research activity (e.g. data, scripts, materials, meta-data) are transparently shared in a consistent and user-friendly way. 

Please use this [form](https://forms.gle/9mHjddrMFGzJzVLa8) to give feedback to the community about our policies, website, or any other thoughts.

## Current Leadership

The current leadership team consists of:

-   Timo Roettger (Chair)

-   Erin M. Buchanan

-   Zed Sehyr

-   Cong Zhang

-   Indranil Dutta

-   Onur Özsoy

-   Simona Amenta

-   Matthew Faytak
