---
title: "Code of Conduct"
date: "2023-08-03"
---

### **Code of conduct for ManyLanguages**

Version 1.1

**This is the current state of the code of conduct. We consider this document a living document. Please be aware that it is subject to changes as our government structure, our tools as well as our channels of communication evolve.**

ManyLanguages is dedicated to providing a welcoming and supportive environment for all people, regardless of background or identity. As such, we do not tolerate behaviour that is disrespectful or that excludes or intimidates others. We do not tolerate discrimination or harassment based on characteristics that include, but are not limited to, sex, gender identity and expression, sexual orientation, disability, physical appearance, body size, citizenship, nationality, ethnic or social origin, pregnancy, familial status, veteran status, genetic information, religion or belief (or lack thereof), membership of a national minority, property, age, education, socio-economic status, technical choices, and experience level. 

### Report an Incident

Please use the following form to report an incident of a code of conduct violation. You may choose to remain anonymous or give your information.

LINK TO A FORM HERE

### **Expected Behaviour** 

All individuals involved in our membership, projects, and communications are expected to show respect and courtesy to others. All interactions should be professional regardless of platform (i.e., either online or in-person). 

To foster a positive and professional environment we encourage the following kinds of behaviours in all ManyLanguages events and communications:

-   Use welcoming and inclusive language 

-   Be respectful of different viewpoints and experiences 

-   Gracefully accept constructive criticism 

-   Focus on what is best for the community 

-   Show courtesy and respect towards other community members 

### **Unacceptable Behaviour** 

Examples of unacceptable behaviour by participants at any ManyLanguages event/platform include (a non-exhaustive list): 

-   Written or verbal comments which have the effect of excluding people on the basis of membership of any specific group 

-   Causing someone to fear for their safety, such as through stalking, following, or intimidation 

-   Violent threats or language directed against another person 

-   The display of sexual or violent images 

-   Unwelcome sexual attention 

-   Non-consensual or unwelcome physical contact 

-   Sustained disruption of talks, events or communications 

-   Insults or put downs 

-   Sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes 

-   Excessive swearing 

-   Incitement to violence, suicide, or self-harm 

-   Continuing to initiate interaction (including photography or recording) with someone after being asked to stop 

-   Publication of private communication without consent 

###  **Consequences of Unacceptable Behaviour** 

Participants who are asked to stop any inappropriate behaviour are expected to comply immediately. This applies to all ManyLanguages events and platforms, either online or in-person. If a participant engages in behaviour that violates this Code of Conduct, the Leadership Team may warn the offender, ask them to leave the event or platform (without refund, if applicable), or engage the Leadership Team to investigate the Code of Conduct violation and impose appropriate sanctions if necessary. 

### **Incident Reporting Guidelines** 

#### **Contact points** 

If someone violates the Code of Conduct during a ManyLanguages related event or communication, we ask that you report it to the event host, organiser, or a designated incident response person. The person you have talked to should make a report to ManyLanguages about the incident by contacting the Leadership Team. If this is not possible for some reason, we would be very grateful if you could report the incident yourself. 

If a violation occurs in an online space outside of organised events, please contact us by completing a report without disclosing your identity via our contact.

#### **What to do if someone is in physical danger**

If you believe someone is in physical danger, please ask a staff member or volunteer to contact appropriate emergency services. All event organisers should, before the event, determine who it would be appropriate to contact in case of an incident. Once the incident has been resolved, we ask that it be reported to the Leadership Team in the same way as all other incidents. 

#### **Code of Conduct Enforcement** 

A detailed enforcement policy is available in the Enforcement Manual below. 

#### **Enforcement Manual** 

This section includes the enforcement manual followed by the Leadership Team. It is used when we respond to an issue to make sure we are consistent and fair. It should be considered an internal document, but we are publishing it publicly in the interests of transparency. Enforcement of the Code of Conduct should be respectful and not include any harassing behaviours. 

#### **The Leadership Team** 

All responses to reports of conduct violations will be managed by the Leadership Team. The Leadership Team may jointly establish a Review Group, made up of independent representatives. One member will be designated chair of the Review Group and will be responsible for all reports back to the Leadership Team. 

#### **How the Leadership Team will respond to reports** 

When a report is sent to the Leadership Team, they will immediately reply to the report to confirm receipt as soon as possible, unless the report is anonymous. This reply should/must be sent within 2 days. If a report does not contain enough information, the Leadership Team will attempt to obtain all relevant data before acting. The Leadership Team is empowered to act on behalf of ManyLanguages in contacting any individuals involved to get a more complete account of events. The Leadership Team is also empowered to act if any of its members become aware of ongoing behaviours that, when taken individually, do not meet a threshold for reporting, nonetheless when considered in aggregate are disrupting or harassing or unacceptable in other ways. 

#### **Urgent Situations: Acting Unilaterally** 

If the incident involves physical danger, or involves a threat to anyone\'s safety (e.g., threats of violence), any member of the Leadership Team and/or the event host, organiser, or a designated incident response person (\"the respondent\") may -- and should -- act unilaterally to protect safety. This action can include contacting law enforcement (or other local personnel) and speaking on behalf of ManyLanguages. 

If the act is ongoing, the respondent may act immediately, before reaching consensus, to diffuse the situation. In ongoing situations, the respondent may at their discretion employ any of the tools available to the Leadership Team, including bans and blocks. In situations where the respondent acts unilaterally, they must inform the Leadership Team members as soon as possible, and report their actions to the Review Group for review within 24 hours.

#### **Less-Urgent Situations** 

Upon receiving a report of an incident, the Leadership Team will inform the Review Group, who will review the incident and determine, to the best of their ability: 

-   whether this is an ongoing situation; 

-   whether there is a threat to anyone\'s physical safety; 

-   what happened; 

-   which part of the Code of Conduct (if any) was violated; 

-   who (if anyone) violated the Code of Conduct. 

This information will be collected in writing, and whenever possible the Review Group\'s deliberations will be recorded and retained (i.e. email discussions, recorded voice conversations, etc.). 

These records will be made available to the Leadership Team and ManyLanguages members, suitably redacted if necessary (e.g., to retain anonymity). 

The Review Group should aim to have a resolution agreed upon within one week. In the event that a resolution cannot be determined at that time, the Review Group will respond to the reporter(s) with an update and projected timeline for resolution. 

#### **Resolutions** 

The Review Group must agree on a resolution by consensus of all members investigating the report in question. If the Review Group cannot reach consensus and deadlocks for over a week, they will turn the matter over to the Leadership Team for resolution. 

Possible responses may include: 

-   Taking no further action (if the Review Group determines no violation occurred). 

-   A private reprimand from the Review Group to the individual(s) involved. In this case, the Review Group chair will deliver that reprimand to the individual(s) over email, cc\'ing the Review Group. 

-   A public announcement of an incident, ideally in the same venue that the violation occurred (i.e., on the listserv for a listserv violation, GitHub for a GitHub violation, etc.). The Review Group may choose to publish this message elsewhere to create a permanent public record. 

-   An imposed suspension (i.e., asking someone to \"take a week off\" from a listserv or the ManyLanguages GitHub or OSF repositories or membership portal platform). The Review Group chair will communicate this suspension to the individual(s). They\'ll be asked to take this suspension voluntarily, but if they do not agree then a temporary ban may be imposed to enforce this vacation. 

-   A permanent or temporary ban from some or all ManyLanguages spaces (listservs, GitHub, OSF groups, membership portal, in-person events including workshops, etc.). The Leadership Team will maintain records of all such bans so that they may be reviewed in the future, extended to new ManyLanguages communication forums, or otherwise maintained. 

-   Assistance to the complainant with a report to other bodies, for example, institutional offices or appropriate law enforcement agencies. 

Once a resolution is agreed upon, but before it is enacted, the Review Group will contact the original reporter and any other affected parties and explain the proposed resolution. The Review Group will ask if this resolution is acceptable and note feedback for the record. However, the Review Group is not required to act on this feedback. 

Finally, the Review Group will make a report to the Leadership Team in the event of an ongoing resolution, such as a ban. 

The Review Group will never publicly discuss the details of the issue; all public statements will be made by the Leadership Team. 

#### **Conflicts of Interest** 

In the event of any conflict of interest (a Leadership member, their family member, or someone with whom the Leadership member has a close academic, personal or employment relationship is involved in a complaint), the Leadership member must immediately notify the other members, and recuse themselves if necessary. 

#### **Maintaining Confidentiality** 

The Leadership members will take care to maintain the confidentiality of information they receive as members of the Code of Conduct enforcement team. This includes names and contact information of the reporters and the reportees (i.e., the people about whom a report has been made). 

Information will be held on file so that repeated violations and small violations over a long period may be recorded, and used to inform appropriate action. This information will be stored securely for 10 years, and accessible only to those with a strict need to know. It will not be used for any other purpose or shared with anyone else. Future members of the Review Group may have access to this information. In some instances, information may be shared with the Leadership Team. 

All Leadership Members commit to treating all members of the ManyLanguages community fairly and with respect at all times. Information they have access to as a result of being a member of the code of conduct enforcement team will not be used for making decisions outside of this role.
