---
title: "Projects"
---

# ML1: ManyTones

Variations in onset fundamental frequency (f0) of vowels have been systematically found to be influenced by the laryngeal states of adjacent consonants — the onset f0 of a vowel is higher following a voiceless compared to a voiced obstruent. This phenomenon, the consonant-related f0 perturbation (CF0), has been considered to be a key source of tonogenesis. Previous findings on phonetic explanations of tonal development include listeners’ ability to detect small CF0 perturbations, use of f0 perturbations as cues for laryngeal contrasts, and the emergence of f0 perturbations as primary cues when other consonantal cues diminish. Despite extensive acoustic and perceptual studies, the understanding of CF0 perception remains limited. This project aims to investigate the perception of minimal perceptible f0 perturbations, both in magnitude and timing, over many languages, and to gain insights on dynamic pitch perception in speech. Additionally, we propose to explore the effects of language background and musical training on CF0 perception. In this proposal, we detail the plans for developing and deploying an online framework for large-scale CF0 perception data that can be made use of by speech laboratories across the globe so as to enrich our knowledge of CF0 informed by many languages.

- Email to reach the team: [manytones\@many-languages.com](mailto:manytones@many-languages.com)

- [Website](https://chenchenzi.github.io/manytones/)

   

# ML2: CLAPS - A Crosslinguistic Approach to Passive Semantics

Passives (e.g., The man was pushed by the woman) have long served as key testing ground for debates between the representation and acquisition of syntax, as well as typological debates surrounding putative linguistic universals. Several recent articles have proposed that, across languages, the passive is associated with the semantic property of affectedness (i.e., “\[B\] (mapped onto the surface \[passive\] subject) is in a state or circumstance characterized by \[A\] (mapped onto the by-object or an understood argument) having acted upon it”. Preliminary support for this claim comes from grammatical-acceptability judgments studies of Balinese, English, Hebrew, Indonesian and Mandarin which found that independently-obtained verb-by-verb ratings of semantic affectedness predict verbs’ acceptability in passive constructions, but not (or, at least, to a significantly lesser extent) active constructions (e.g., The woman pushed the man) or pseudo-passive topicalizization/focus constructions (e.g., The man, the woman pushed). The CLAPS project investigates whether this finding generalizes to a wider sample of typologically-distinct languages, and thus provides important new evidence regarding the claim that this semantic property of the passive constitutes a typological universal.

- Email to reach the team: [ben.ambridge at manchester dot ac dot uk](mailto:ben.ambridge@manchester.ac.uk)

# ML3: Many Uses

Norms are essential for quantifying relations between words. These relations are often assessed via associative and semantic norms, but these measures may overlook how interactive properties also shape a word’s meaning. Recently, Maxwell et al. (2024) explored this possibility by developing a set of affordance norms for concrete nouns, which measured perceived actor-object interactions. Using an open-ended response format, the authors computed three affordance measures for 2825 concrete English nouns: Affordance strength (AFS), affordance proportion (AFP), and affordances set size (AFSS). These measures correlated with embodied ratings (e.g., body-object interaction (BOI) and sensorimotor strength) but showed low overlap with associative/semantic measures. This suggests that affordance measures capture unique information relative to associative/semantic norms. Our proposed study will build upon this work in two ways. First, we will expand Maxwell et al.’s English norms, providing greater overlap with previously normed datasets. Second, we will extend data collection to six additional languages. Across all languages, we will test for correlations between affordance embodied measures (Aim 1), affordance and associative/semantic measures (Aim 2), and test whether AFSS can predict semantic priming effects (Aim 3). Finally, we will explore whether affordance norms are consistent across our target languages (Aim 4).

- Email to reach the team: [nicholas.maxwell at msutexas dot edu](mailto:nicholas.maxwell@msutexas.edu)
